version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    secrets:
      - mysecret
    environment:
      - FLASK_ENV=development

secrets:
  mysecret:
    file: ./secrets/dummy-secret.txt
